/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medical_store;

import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author abhishek
 */
public class Owner_Manage_Medicine extends javax.swing.JFrame {

    /**
     * Creates new form Owner_Manage_Medicine
     */
    public Owner_Manage_Medicine() {
        initComponents();
        setSearchItem(search_view, "medicine", "medc_name");
        setSearchItem(search_update, "medicine", "medc_name");
        setSearchItem(supplier_name_add, "supplier", "supplier_name");
        setSearchItem(supplier_name_update, "supplier", "supplier_name");
        setSearchItem(medicine_type_add, "medicine_type", "type_name");
        setSearchItem(medicine_type_update, "medicine_type", "type_name");
    }
    
    public Owner_Manage_Medicine(int panel, String name) {
        initComponents();
        setSearchItem(search_view, "medicine", "medc_name");
        setSearchItem(search_update, "medicine", "medc_name");
        setSearchItem(supplier_name_add, "supplier", "supplier_name");
        setSearchItem(supplier_name_update, "supplier", "supplier_name");
        setSearchItem(medicine_type_add, "medicine_type", "type_name");
        setSearchItem(medicine_type_update, "medicine_type", "type_name");
        this.setVisible(true);
        jTabbedPane1.setSelectedIndex(panel);
        if(panel == 2) {
            search_update.setSelectedItem(name);
        }
    }

    private void setSearchItem(JComboBox component, String table, String column) {
        try(Connection conn = MySQL_Connector.getConnection()) {
            String conn_query = "select " + column + " from " + table;
            ResultSet res = MySQL_Connector.runQuery(conn, conn_query);
            while(res.next()) {
                component.addItem(res.getString(column));
            }
            component.setVisible(true);
            conn.close();
            res.close();
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        generate_bill_button = new javax.swing.JButton();
        manage_medicine_button = new javax.swing.JButton();
        manage_stocks_button = new javax.swing.JButton();
        manage_employees_button = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search_view = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_view = new javax.swing.JTable();
        delete_button_view = new javax.swing.JButton();
        update_button_view = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        medicine_name_add = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        supplier_name_add = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        medicine_type_add = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        medicine_per_strip_add = new javax.swing.JTextField();
        cost_per_strip_add = new javax.swing.JTextField();
        shelf_number_add = new javax.swing.JTextField();
        medicine_description_add = new javax.swing.JTextField();
        cancel_button_add = new javax.swing.JButton();
        add_medicine_button_add = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        medicine_power_add = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        available_quantity_add = new javax.swing.JTextField();
        update_panel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        search_update = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        medicine_name_update = new javax.swing.JTextField();
        medicine_per_strip_update = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cost_per_strip_update = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        supplier_name_update = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        medicine_type_update = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        shelf_number_update = new javax.swing.JTextField();
        medicine_description_update = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        update_medicine_button_update = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cancel_button_update = new javax.swing.JButton();
        medicine_power_update = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        available_quantity_update = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Medicines");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Navigation"));

        generate_bill_button.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        generate_bill_button.setText("Generate Bill");
        generate_bill_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate_bill_buttonActionPerformed(evt);
            }
        });

        manage_medicine_button.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        manage_medicine_button.setForeground(new java.awt.Color(201, 45, 45));
        manage_medicine_button.setText("Manage Medicines");
        manage_medicine_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_medicine_buttonActionPerformed(evt);
            }
        });

        manage_stocks_button.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        manage_stocks_button.setText("Manage Stocks");
        manage_stocks_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_stocks_buttonActionPerformed(evt);
            }
        });

        manage_employees_button.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        manage_employees_button.setText("Manage Employees");
        manage_employees_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_employees_buttonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1.setText("Manage Defects");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(manage_medicine_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(generate_bill_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manage_stocks_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manage_employees_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(generate_bill_button)
                .addGap(34, 34, 34)
                .addComponent(manage_medicine_button)
                .addGap(35, 35, 35)
                .addComponent(manage_stocks_button)
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addGap(37, 37, 37)
                .addComponent(manage_employees_button)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        jTabbedPane1.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel1.setText("Search the medicine:");

        search_view.setEditor(null);
        search_view.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                search_viewItemStateChanged(evt);
            }
        });
        search_view.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                search_viewFocusGained(evt);
            }
        });
        search_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_viewActionPerformed(evt);
            }
        });

        table_view.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Medicine ID", null},
                {"Medicine Company", null},
                {"Medicine Description", null},
                {"Medicine Power", null},
                {"Available Quantity", null},
                {"Cost/Strip", null},
                {"Medicines/Strip", null},
                {"Shelf Number", null}
            },
            new String [] {
                "Term", "Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_view.setRowHeight(29);
        table_view.setRowMargin(2);
        jScrollPane2.setViewportView(table_view);

        delete_button_view.setText("Delete");
        delete_button_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_button_viewActionPerformed(evt);
            }
        });

        update_button_view.setText("Update ");
        update_button_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_button_viewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(delete_button_view, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(update_button_view, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(search_view, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(search_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delete_button_view)
                    .addComponent(update_button_view))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View Medicine", jPanel1);

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel2.setText("Medicine Name:");

        medicine_name_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicine_name_addActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel3.setText("Supplier Name:");

        jLabel4.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel4.setText("Medicine Type:");

        jLabel5.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel5.setText("Medicine Per Strip:");

        jLabel6.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel6.setText("Cost Per Strip:");

        jLabel7.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel7.setText("Shelf Number:");

        jLabel8.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel8.setText("Description:");

        cost_per_strip_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cost_per_strip_addActionPerformed(evt);
            }
        });

        medicine_description_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicine_description_addActionPerformed(evt);
            }
        });

        cancel_button_add.setText("Cancel");
        cancel_button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_button_addActionPerformed(evt);
            }
        });

        add_medicine_button_add.setText("Add Medicine");
        add_medicine_button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_medicine_button_addActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel17.setText("Medicine Power");

        jLabel18.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel18.setText("Available Quantity");

        available_quantity_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                available_quantity_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(add_medicine_button_add)
                        .addGap(65, 65, 65)
                        .addComponent(cancel_button_add, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel17))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(supplier_name_add, 0, 157, Short.MAX_VALUE)
                            .addComponent(medicine_type_add, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(medicine_name_add)
                            .addComponent(medicine_power_add))
                        .addGap(125, 125, 125)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(medicine_per_strip_add, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(cost_per_strip_add, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(shelf_number_add, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(available_quantity_add))))
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 140, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(54, 54, 54)
                .addComponent(medicine_description_add, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(medicine_per_strip_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medicine_name_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(supplier_name_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cost_per_strip_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(medicine_type_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(shelf_number_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(medicine_power_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(available_quantity_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(medicine_description_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_medicine_button_add)
                    .addComponent(cancel_button_add))
                .addGap(35, 35, 35))
        );

        jTabbedPane1.addTab("Add Medicine", jPanel2);

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel9.setText("Search the medicine:");

        search_update.setEditor(null);
        search_update.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                search_updateItemStateChanged(evt);
            }
        });
        search_update.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                search_updateFocusGained(evt);
            }
        });
        search_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_updateActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel10.setText("Medicine Name:");

        medicine_name_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicine_name_updateActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel11.setText("Medicine Per Strip:");

        cost_per_strip_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cost_per_strip_updateActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel12.setText("Cost Per Strip:");

        jLabel13.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel13.setText("Supplier Name:");

        jLabel14.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel14.setText("Medicine Type:");

        jLabel15.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel15.setText("Shelf Number:");

        medicine_description_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicine_description_updateActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel16.setText("Description:");

        update_medicine_button_update.setText("Update Medicine");
        update_medicine_button_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_medicine_button_updateActionPerformed(evt);
            }
        });

        jSeparator1.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N

        cancel_button_update.setText("Cancel");
        cancel_button_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_button_updateActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel19.setText("Medicine Power");

        jLabel20.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel20.setText("Available Quantity");

        javax.swing.GroupLayout update_panelLayout = new javax.swing.GroupLayout(update_panel);
        update_panel.setLayout(update_panelLayout);
        update_panelLayout.setHorizontalGroup(
            update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(update_panelLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel9)
                .addGap(43, 43, 43)
                .addComponent(search_update, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(update_panelLayout.createSequentialGroup()
                .addGroup(update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(update_panelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(update_panelLayout.createSequentialGroup()
                                .addGroup(update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(71, 71, 71)
                                .addGroup(update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(supplier_name_update, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(medicine_type_update, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(medicine_name_update, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(update_panelLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(71, 71, 71)
                                .addComponent(medicine_power_update)))
                        .addGap(125, 125, 125)
                        .addGroup(update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel15)
                            .addComponent(jLabel12)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(available_quantity_update)
                            .addComponent(medicine_per_strip_update, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(cost_per_strip_update, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(shelf_number_update, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, update_panelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(update_medicine_button_update)
                        .addGap(54, 54, 54)
                        .addComponent(cancel_button_update, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, update_panelLayout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(54, 54, 54)
                .addComponent(medicine_description_update, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        update_panelLayout.setVerticalGroup(
            update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(update_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(search_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(medicine_name_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(medicine_per_strip_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(supplier_name_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(cost_per_strip_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(medicine_type_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(shelf_number_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(medicine_power_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(available_quantity_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(medicine_description_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_medicine_button_update)
                    .addComponent(cancel_button_update))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Update Medicine", update_panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jTabbedPane1)
                .addGap(251, 251, 251))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("tab1t3xt");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showInformationTable(JComboBox component, JTable table) {
        try(Connection conn = MySQL_Connector.getConnection()) {
            String medicine_name = component.getSelectedItem().toString();
            String query = "select * from medicine where medc_name = '" + medicine_name + "'";
            ResultSet rs = MySQL_Connector.runQuery(conn, query);
            if(rs.next())
                table.setValueAt(rs.getString("medc_id"), 0, 1);
                String query2 = "select supplier_name from supplier where supplier_id = '" + rs.getString("medc_supplier_id") + "'";
                ResultSet rs1 = MySQL_Connector.runQuery(conn, query2);
                if(rs1.next()) {
                    table.setValueAt(rs1.getString("supplier_name"), 1, 1);
                }
                table.setValueAt(rs.getString("medc_per_strip"), 6, 1);
                table.setValueAt(rs.getString("medc_cost_per_strip"), 5, 1);
                table.setValueAt(rs.getString("shelf_no"), 7, 1);
                //JTable_info.setValueAt(rs.getString("medc_quantity"), 4, 1);
                table.setValueAt(rs.getString("medc_description"), 2,1);
                table.setValueAt(rs.getString("medc_power"), 3, 1);
                table.setValueAt(rs.getString("medc_quantity_in_tablets"), 4, 1);
                conn.close();
                rs.close();
                rs1.close();
        }catch(SQLException e) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    public void showInformationToUpdate() {
        try {
            String name = search_update.getSelectedItem().toString();
            Connection conn = null;
            conn = MySQL_Connector.getConnection();
            String query = "select * from medicine where medc_name = '" + name + "'";
            ResultSet rs = MySQL_Connector.runQuery(conn, query);
            if(rs == null) {
                JOptionPane.showMessageDialog(null, "Failed to obtain data from database. Try after some time.");
            }
            else if(rs.next()) {
                medicine_name_update.setText(rs.getString("medc_name"));
                medicine_description_update.setText(rs.getString("medc_description"));
                medicine_per_strip_update.setText(rs.getString("medc_per_strip"));
                cost_per_strip_update.setText(rs.getString("medc_cost_per_strip"));
                shelf_number_update.setText(rs.getString("shelf_no"));
                medicine_power_update.setText(rs.getString("medc_power"));
                available_quantity_update.setText(rs.getString("medc_quantity_in_tablets"));
                supplier_name_update.setSelectedItem(supplier_name_update.getItemAt(Integer.parseInt(rs.getString("medc_supplier_id")) - 1));
                medicine_type_update.setSelectedItem(medicine_type_update.getItemAt(Integer.parseInt(rs.getString("medc_type_id")) - 1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Owner_Manage_Medicine.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void manage_medicine_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_medicine_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manage_medicine_buttonActionPerformed

    private void search_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_viewActionPerformed
        showInformationTable(search_view, table_view);
    }//GEN-LAST:event_search_viewActionPerformed

    private void medicine_name_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicine_name_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicine_name_addActionPerformed

    private void cost_per_strip_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cost_per_strip_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cost_per_strip_addActionPerformed

    private void medicine_description_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicine_description_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicine_description_addActionPerformed

    private void search_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_updateActionPerformed
        showInformationToUpdate();
    }//GEN-LAST:event_search_updateActionPerformed

    private void medicine_name_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicine_name_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicine_name_updateActionPerformed

    private void cost_per_strip_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cost_per_strip_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cost_per_strip_updateActionPerformed

    private void medicine_description_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicine_description_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicine_description_updateActionPerformed

    private void update_medicine_button_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_medicine_button_updateActionPerformed
        int result = JOptionPane.showConfirmDialog(rootPane, "Do you really want to update " + search_update.getSelectedItem().toString() + "?");
        if(result == 1 || result == 2) {
            return;
        }
        try {
            String name = medicine_name_update.getText();
            String description = medicine_description_update.getText();
            String medicine_per_strip = medicine_per_strip_update.getText();
            String cost = cost_per_strip_update.getText();
            String shelf = shelf_number_update.getText();
            String power = medicine_power_update.getText();
            String quantity = available_quantity_update.getText();
            int supplier = supplier_name_update.getSelectedIndex();
            int type = medicine_type_update.getSelectedIndex();
            
            supplier++;
            type++;
            
            Connection conn = MySQL_Connector.getConnection();
            String query = "update medicine set medc_name = '" + name + "', medc_supplier_id = " + supplier + ", medc_type_id = " + type + ", medc_per_strip = " + (int)Float.parseFloat(medicine_per_strip) + ", medc_cost_per_strip = " + (int)Float.parseFloat(cost) + ", medc_description = '" + description + "', shelf_no = '" + shelf + "', medc_power = " + Integer.parseInt(power) + ", medc_quantity_in_tablets = " + Integer.parseInt(quantity) + " where medc_name = '" + search_update.getSelectedItem().toString() + "'";
            MySQL_Connector.runUpdateQuery(conn, query);
            
            this.setVisible(false);
            Owner_Manage_Medicine window = new Owner_Manage_Medicine(2, name);
        } catch (SQLException ex) {
            Logger.getLogger(Owner_Manage_Medicine.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_update_medicine_button_updateActionPerformed

    private void add_medicine_button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_medicine_button_addActionPerformed
        int result = JOptionPane.showConfirmDialog(rootPane, "Do you really want to add " + medicine_name_add.getText() + " to the database?");
        if(result == 1 || result == 2) {
            return;
        }
        try {
            String name = medicine_name_add.getText();
            String description = medicine_description_add.getText();
            String medicine_per_strip = medicine_per_strip_add.getText();
            String cost = cost_per_strip_add.getText();
            String shelf = shelf_number_add.getText();
            String power = medicine_power_add.getText();
            String quantity = available_quantity_add.getText();
            int supplier = supplier_name_add.getSelectedIndex();
            int type = medicine_type_add.getSelectedIndex();
                
            supplier++;
            type++;
            
            Connection conn = MySQL_Connector.getConnection();
            String query = "select medc_id from medicine order by medc_id desc limit 1";
            ResultSet rs = MySQL_Connector.runQuery(conn, query);
            String id = null;
            
            if(rs == null) {
                JOptionPane.showMessageDialog(null, "Failed to connect to the database. Try again after some time."); 
            }
            if(rs.next()) {
                id = rs.getString("medc_id");
            }
            else {
                id = "medc0";
            }
            String text = "", num = "";
            for(char ch : id.toCharArray()) {
                if(Character.isDigit(ch)) {
                    num += ch;
                }
                else {
                    text += ch;
                }
            }
            id = text + (Integer.parseInt(num) + 1);
            
            query = "insert into medicine values ('" + id + "', '" + name + "', " + supplier + ", " + type + ", " + (int)Float.parseFloat(medicine_per_strip) + ", " + (int)Float.parseFloat(cost) + ", '" + description + "', '" + shelf + "', " +Integer.parseInt(quantity)+ ", " +Integer.parseInt(power)+ ")";
            MySQL_Connector.runUpdateQuery(conn, query);
            
            this.setVisible(false);
            Owner_Manage_Medicine window = new Owner_Manage_Medicine(1, null);
            
        } catch (SQLException ex) {
            Logger.getLogger(Owner_Manage_Medicine.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_add_medicine_button_addActionPerformed

    private void generate_bill_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate_bill_buttonActionPerformed
        Owner_Generate_Bill window = new Owner_Generate_Bill();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_generate_bill_buttonActionPerformed

    private void update_button_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_button_viewActionPerformed
        jTabbedPane1.setSelectedIndex(2);
        search_update.setSelectedItem(search_view.getSelectedItem());
        //JOptionPane.showMessageDialog(null, jComboBox1.getSelectedItem().toString());
        
    }//GEN-LAST:event_update_button_viewActionPerformed

    private void available_quantity_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_available_quantity_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_available_quantity_addActionPerformed

    private void search_viewItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_search_viewItemStateChanged
        showInformationTable(search_view, table_view);
    }//GEN-LAST:event_search_viewItemStateChanged

    private void search_viewFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_viewFocusGained
        showInformationTable(search_view, table_view);
    }//GEN-LAST:event_search_viewFocusGained

    private void delete_button_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_button_viewActionPerformed
        int result = JOptionPane.showConfirmDialog(rootPane, "Do you really want to delete this entry?");
        if(result == 1 || result == 2) {
            return;
        }
        String query = "delete from medicine where medc_id = '" + table_view.getValueAt(0, 1).toString() + "'";
        try(Connection conn = MySQL_Connector.getConnection()) {
            MySQL_Connector.runUpdateQuery(conn, query);
            JOptionPane.showMessageDialog(null, "Entry Deleted Successfully!");
        }catch(SQLException e) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_delete_button_viewActionPerformed

    private void search_updateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_search_updateItemStateChanged
        showInformationToUpdate();
    }//GEN-LAST:event_search_updateItemStateChanged

    private void search_updateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_updateFocusGained
        showInformationToUpdate();
    }//GEN-LAST:event_search_updateFocusGained

    private void cancel_button_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_button_updateActionPerformed
        int result = JOptionPane.showConfirmDialog(rootPane, "Do you really want to cancel? Your entered infomation will be lost.");
        if(result == 1 || result == 2) {
            return;
        }
        showInformationToUpdate();
    }//GEN-LAST:event_cancel_button_updateActionPerformed

    private void cancel_button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_button_addActionPerformed
        int result = JOptionPane.showConfirmDialog(rootPane, "Do you really want to cancel? Your entered infomation will be lost.");
        if(result == 1 || result == 2) {
            return;
        }
        medicine_name_add.setText("");
        medicine_description_add.setText("");
        medicine_per_strip_add.setText("");
        cost_per_strip_add.setText("");
        shelf_number_add.setText("");
        medicine_power_add.setText("");
        available_quantity_add.setText("");
        supplier_name_add.setSelectedItem(supplier_name_add.getItemAt(0));
        medicine_type_add.setSelectedItem(medicine_type_add.getItemAt(0));
    }//GEN-LAST:event_cancel_button_addActionPerformed

    private void manage_stocks_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_stocks_buttonActionPerformed
        Manage_Stocks window = new Manage_Stocks();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_manage_stocks_buttonActionPerformed

    private void manage_employees_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_employees_buttonActionPerformed
        this.setVisible(false);
        Owner_Manage_Employee window = new Owner_Manage_Employee();
        window.setVisible(true);
    }//GEN-LAST:event_manage_employees_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        Manage_Defects window = new Manage_Defects();
        window.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Owner_Manage_Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Owner_Manage_Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Owner_Manage_Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Owner_Manage_Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Owner_Manage_Medicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_medicine_button_add;
    private javax.swing.JTextField available_quantity_add;
    private javax.swing.JTextField available_quantity_update;
    private javax.swing.JButton cancel_button_add;
    private javax.swing.JButton cancel_button_update;
    private javax.swing.JTextField cost_per_strip_add;
    private javax.swing.JTextField cost_per_strip_update;
    private javax.swing.JButton delete_button_view;
    private javax.swing.JButton generate_bill_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton manage_employees_button;
    private javax.swing.JButton manage_medicine_button;
    private javax.swing.JButton manage_stocks_button;
    private javax.swing.JTextField medicine_description_add;
    private javax.swing.JTextField medicine_description_update;
    private javax.swing.JTextField medicine_name_add;
    private javax.swing.JTextField medicine_name_update;
    private javax.swing.JTextField medicine_per_strip_add;
    private javax.swing.JTextField medicine_per_strip_update;
    private javax.swing.JTextField medicine_power_add;
    private javax.swing.JTextField medicine_power_update;
    private javax.swing.JComboBox<String> medicine_type_add;
    private javax.swing.JComboBox<String> medicine_type_update;
    private javax.swing.JComboBox<String> search_update;
    private javax.swing.JComboBox<String> search_view;
    private javax.swing.JTextField shelf_number_add;
    private javax.swing.JTextField shelf_number_update;
    private javax.swing.JComboBox<String> supplier_name_add;
    private javax.swing.JComboBox<String> supplier_name_update;
    private javax.swing.JTable table_view;
    private javax.swing.JButton update_button_view;
    private javax.swing.JButton update_medicine_button_update;
    private javax.swing.JPanel update_panel;
    // End of variables declaration//GEN-END:variables
}
